services:

  redis:
    image: redis:7-alpine
    container_name: traffic-control-redis
    ports:
      - "6379:6379"

  gateway-1:
    image: distributed-traffic-control:latest
    container_name: traffic-control-gateway-1
    depends_on:
      - redis
    environment:
      SERVER_PORT: 8081
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ID: gateway-1
      LEASE_DURATION: PT30S
      LEASE_CAPACITY: 10
    ports:
      - "8081:8081"

  gateway-2:
    image: distributed-traffic-control:latest
    container_name: traffic-control-gateway-2
    depends_on:
      - redis
    environment:
      SERVER_PORT: 8081
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ID: gateway-2
      LEASE_DURATION: PT30S
      LEASE_CAPACITY: 10
    ports:
      - "8082:8081"

  gateway-3:
    image: distributed-traffic-control:latest
    container_name: traffic-control-gateway-3
    depends_on:
      - redis
    environment:
      SERVER_PORT: 8081
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ID: gateway-3
      LEASE_DURATION: PT30S
      LEASE_CAPACITY: 10
    ports:
      - "8083:8081"

  prometheus:
    image: prom/prometheus:latest
    container_name: traffic-control-prometheus
    depends_on:
      - gateway-1
      - gateway-2
      - gateway-3
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: traffic-control-grafana
    depends_on:
      - prometheus
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"