spring.application.name=distributed-traffic-control

server.port=${SERVER_PORT:8081}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

allocation.node-id=${NODE_ID:local-node}
allocation.lease-duration=${LEASE_DURATION:PT30S}
allocation.lease-capacity=${LEASE_CAPACITY:10}

management.endpoints.web.exposure.include=health,info,prometheus


# OpenTelemetry tracing
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:1.0}

# Do not export application metrics to Jaeger
management.otlp.metrics.export.enabled=false

