global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: traffic-control-gateways
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - gateway-1:8081
          - gateway-2:8081
          - gateway-3:8081